### PR TITLE
Website text improvements

### PR DESCRIPTION
**Pull request by thecoder876**
Improved text on top of upload button and the text that is shown if the browser is detected as IE 9 or lower.

### CODE REVIEW

**Comment by thecoder876** [comment]
*Ping* @Touchcreator

**Comment by thecoder876** [comment]
@DabDatBass?

**Comment by DabDatBass** [comment]
I mean- Barely anybody has IE 9. The webpage works better on modern browsers. 

Chrome: https://www.google.com/chrome/
Firefox: https://www.mozilla.org/en-US/firefox/new/
Edge: https://www.microsoft.com/en-us/edge
Opera (have not tested): https://www.opera.com/

**Comment by thecoder876** [comment]
> I mean- Barely anybody has IE 9. The webpage works better on modern browsers.
> 
> Chrome: https://www.google.com/chrome/
> Firefox: https://www.mozilla.org/en-US/firefox/new/
> Edge: https://www.microsoft.com/en-us/edge
> Opera (have not tested): https://www.opera.com/

@DabDatBass Ok, also btw I use Opera and it works fine.

**Comment by wgyt** [comment]
@thecoder876 @DabDatBass this is a nice feature, I´m merging this pr

**Pull request merged**
